### ISSUE TITLE
Why WCAG_TARGET_SIZE = 48;

### ISSUE THREAD

**Issue by jnurthen** [dequelabs/axe-android#12]
WCAG 2.1 has a target size of 44. Why is 48 used in /src/main/java/com/deque/axe/android/rules/hierarchy/TouchSizeWcag.java ?

**Comment by jnurthen** [comment]
see https://www.w3.org/TR/WCAG21/#target-size

**Comment by chriscm2006** [comment]
Oversight from a version of this rule that used Material Design spec instead. Looks like we changed the name of the variable but not the value.
