### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by Schwoader123** [dequelabs/axe-android#155]
[axe-android-1.1.1.zip](https://github.com/dequelabs/axe-android/files/7621483/axe-android-1.1.1.zip)

**Comment by Schwoader123** [comment]
Duplicate of #

**Comment by Schwoader123** [comment]
[axe-android-1.1.1.zip](https://github.com/dequelabs/axe-android/files/7621490/axe-android-1.1.1.zip)

**Comment by karnett** [comment]
Closing for Incomplete Information
