### ISSUE TITLE
Text in larger font size cut off

### ISSUE THREAD

**Issue by jbuller** [dequelabs/axe-android#19]
Using my Android phone with a large text size I find I am unable to read some of the text I should be able to (the screen does not scroll). See screenshots 
![Screenshot_20190411-091904_axe](https://user-images.githubusercontent.com/1532534/55947768-094d3900-5c47-11e9-9e7e-8105c5af79ea.jpg)
![Screenshot_20190411-092323_axe](https://user-images.githubusercontent.com/1532534/55947769-09e5cf80-5c47-11e9-9917-1e721257c718.jpg)
![Screenshot_20190411-092758_axe](https://user-images.githubusercontent.com/1532534/55947773-0a7e6600-5c47-11e9-962a-7e84f25e9e5a.jpg)

**Comment by chriscm2006** [comment]
@cyono-deque This is an easy fix, we should squeak this into next release.

**Comment by cyono-deque** [comment]
Resolved and released.
