### ISSUE TITLE
Project Setup walkthrough

### ISSUE THREAD

**Issue by svshubhm** [dequelabs/axe-android#20]
Hello Sir, I am a student, just saw your session "Mobile office hours:Axe for Android"
can you please guide me through the project setup walkthrough?

here is my email address : svshubham11@gmail.com.

Thanking you in Anticipation!

**Comment by chriscm2006** [comment]
Can you define "Project Setup Walthrough". Are you attempting to set up your own project based on this library?

**Comment by svshubhm** [comment]
Yes Sir.

**Comment by chriscm2006** [comment]
This is not something we can facilitate individually, however, if you reach out to Deque's marketing department we may be able to make it a topic for the next Office Hours.

**Comment by svshubhm** [comment]
Okay Sir, Thank you!
