### ISSUE TITLE
Example Application

### ISSUE THREAD

**Issue by benbadio** [dequelabs/axe-android#28]
The README is informative but an example app would help developers understand how to implement this api. Please consider adding an example app, or possibly just adding more code snippets to the README. In particular it would be nice to see examples of the Axe interfaces being implemented.

**Comment by chriscm2006** [comment]
This issue should also answer the concerns of #29. 

@benbadio in the near future I am going to massage this issue a bit, to reflect a few additional documentation needs so that we can capture some of those needs under a bigger issue, rather than tracking individual ones.

**Comment by wispy316** [comment]
Some progress now?

**Comment by rushby** [comment]
Hi guys just looking to implement accessible checks in our project and keen to use this library.  Lack of an example project is off putting, any progress on this at all or is anyone aware of someone else's project that has got this working?

**Comment by skelzor06** [comment]
Any news on this issue?
