### ISSUE TITLE
Maven Central Publishing

### ISSUE THREAD

**Issue by chriscm2006** [dequelabs/axe-android#67]
Publish axe-android to maven central.

**Comment by chriscm2006** [comment]
- Talk to Dave Musser/Doug Nelson about Maven Central Account

**Comment by chriscm2006** [comment]
I have added our password and api key to our CircleCI Context.

**Comment by devchan4188** [comment]
Reopened this issue, working with Chris on this.

**Comment by devchan4188** [comment]
This issue has been resolved, the fix will be available in 0.1.17
