### ISSUE TITLE
axe for Android issue: impossible to scroll to see highlighted violations 

### ISSUE THREAD

**Issue by kensgists** [dequelabs/axe-android#99]
This applies to axe for Android. Not sure if this is the place. Please let me know where to report issues with the Android app, if not....

Many native apps have toolbars that are fixed at the bottom of the viewport. Because the app occupies the bottom and cannot be moved elsewhere, there appears to be no way to view issues that are discovered when already scrolled to the bottom of a view -- issues are "under" the axe for Android toolbar.

**Comment by cyono** [comment]
Thank you for pointing this out!
